name: Meta Creative Score + Downloads + AI (Weekly)
on:
  schedule:
    # Segunda-feira 06:00 BRT (UTC-3) = 09:00 UTC
    - cron: "0 9 * * 1"
  workflow_dispatch:
jobs:
  pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: write
    env:
      META_ACCESS_TOKEN: ${{ secrets.META_ACCESS_TOKEN }}
      META_AD_ACCOUNT_ID: ${{ secrets.META_AD_ACCOUNT_ID }}
      META_CAMPAIGN_ID: "120240998569260670"
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      SLACK_CHANNEL_EMAIL: ${{ secrets.SLACK_CHANNEL_EMAIL }}
      TZ: America/Sao_Paulo
      # IA
      AI_PROVIDER: ${{ secrets.AI_PROVIDER }}
      AI_ENDPOINT_URL: ${{ secrets.AI_ENDPOINT_URL }}
      AI_API_KEY: ${{ secrets.AI_API_KEY }}
      AI_MODEL: ${{ secrets.AI_MODEL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps (ffmpeg)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install moviepy pillow openai

      # ============================================
      # PASSO 1: Download dos criativos (PRIMEIRO!)
      # ============================================
      - name: Download creatives
        run: |
          echo "=== PASSO 1: Download dos criativos ==="
          python download_creatives.py

      # ============================================
      # PASSO 2: Calcular Performance Score
      # ============================================
      - name: Run performance score
        run: |
          echo "=== PASSO 2: Calculando scores ==="
          python "Performance Score.py"

      # ============================================
      # PASSO 3: Consolidar dados (linkar scores aos criativos)
      # ============================================
      - name: Consolidate data
        run: |
          echo "=== PASSO 3: Consolidando dados ==="
          python consolidate_data.py

      # ============================================
      # PASSO 4: Análise IA (com dados consolidados)
      # ============================================
      - name: AI analyze creatives
        run: |
          echo "=== PASSO 4: Análise de IA ==="
          python ai_analyze_creatives.py

      # ============================================
      # PASSO 5: Gerar relatório qualitativo
      # ============================================
      - name: Generate qualitative report
        run: |
          echo "=== PASSO 5: Gerando relatório qualitativo ==="
          python generate_qualitative_report.py

      # ============================================
      # PASSO 6: Atualizar playbook de boas práticas
      # ============================================
      - name: Update creative playbook
        run: |
          echo "=== PASSO 6: Atualizando playbook ==="
          python update_playbook.py

      # Debug: verificar arquivos gerados
      - name: Debug output
        if: always()
        run: |
          echo "---- LS creatives_output ----"
          ls -la creatives_output || true
          echo "---- LS analysis ----"
          ls -la creatives_output/analysis || true
          echo "---- Consolidated JSON ----"
          head -n 50 creatives_output/consolidated_data.json || true

      # Commit de arquivos gerados
      - name: Commit generated files
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main || true
          git add history/ creative_score_automation.csv creatives_output/ ai_cache/ summary_email.txt playbook/ reports/ || true
          git diff --cached --quiet || git commit -m "chore: weekly run outputs (run $GITHUB_RUN_ID)"
          git push || true

      # Artifacts (backup)
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: meta-pipeline-output
          path: |
            history/*.csv
            creative_score_automation.csv
            creatives_output/**
            ai_cache/**
            playbook/**
            reports/**
            summary_email.txt
            *.log
          if-no-files-found: warn

      # Envia email no Slack
      - name: Notify Slack via Email
        if: always()
        continue-on-error: true
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ env.EMAIL_USERNAME }}
          password: ${{ env.EMAIL_PASSWORD }}
          subject: Meta Pipeline — ${{ job.status }}
          to: ${{ env.SLACK_CHANNEL_EMAIL }}
          from: Meta Pipeline <${{ env.EMAIL_USERNAME }}>
          body: |
            Status: ${{ job.status }}
            Repo: ${{ github.repository }}
            Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Obs: O resumo detalhado do score está em summary_email.txt (artifacts / repo).
